### ISSUE TITLE
[JOSS REVIEW] Installation in GitHub Actions is failing

### ISSUE THREAD

**Issue by devarops** [rikenbit/iTensor#1]
Hello @kokitsuyuzaki 👋

Congratulations on your submission to JOSS! Your paper and software look great, and I'm sure it will be published soon.

I am one of the reviewers assigned to your paper, and I'm currently going through the checklist provided by JOSS. One of the items I was asked to check is that the installation proceeds as outlined in the documentation. I tried to install the package but encountered difficulties. I encountered the same error that is visible in your GitHub Actions pipeline.

```
── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘/tmp/RtmpXxRqzz/remotes72037c724/rikenbit-iTensor-30b56f9/DESCRIPTION’ ... OK
* preparing ‘iTensor’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted ‘LazyData’ from DESCRIPTION
* building ‘iTensor_1.0.2.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
ERROR: dependency ‘mixOmics’ is not available for package ‘iTensor’
* removing ‘/usr/local/lib/R/site-library/iTensor’
Warning messages:
1: package ‘mixOmics’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In i.p(...) :
  installation of package ‘/tmp/RtmpXxRqzz/file743a34e1a/iTensor_1.0.2.tar.gz’ had non-zero exit status
Error in find.package(pkg, lib.loc) : 
  there is no package called ‘iTensor’
Calls: <Anonymous> -> find.package
Execution halted
The command '/bin/sh -c R -e "BiocManager::install('mixOmics'); devtools::install_github('rikenbit/iTensor',     upgrade='always', force=TRUE, INSTALL_opts = '--install-tests');    tools::testInstalledPackage('iTensor')"' returned a non-zero code: 1
```

Could you please fix the Docker image build? That way, I could confirm that the software installs in GitHub Actions as expected.

Looking forward to your response. Thank you!

**Comment by devarops** [comment]
I am unable to install the package. I get the following error message:

```
ERROR: dependency ‘mixOmics’ is not available for package ‘iTensor’
```

**Comment by kokitsuyuzaki** [comment]
Hi, @devarops

Thanks for taking on the role of reviewer!

This error is probably due to the ERROR of mixOmics in devel (v3.18) branch of Bioconductor.
https://www.bioconductor.org/checkResults/3.18/bioc-LATEST/mixOmics/
https://bioconductor.org/packages/3.18/bioc/html/mixOmics.html

I modified the Dockerfile to pull the release version (v3.17) of Bioconductor's Docker image, and GitHub Actions has worked properly.
https://github.com/rikenbit/iTensor/blob/main/Dockerfile
https://github.com/rikenbit/iTensor/commit/96ebbbb051728d865cce25712e6420f52f294deb

Could you check it again?

**Comment by devarops** [comment]
It's fixed.
