### ISSUE TITLE
R package loading fails due to mixOmics

### ISSUE THREAD

**Issue by ritika-giri** [rikenbit/iTensor#3]
When I load iTensor in the R workspace using `install.packages("iTensor")`  and `library(iTensor)` as mentioned in the paper, I get the following error message:

```
Error: package or namespace load failed for ‘iTensor’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘mixOmics’
```

It works after I install mixOmics manually as:
```
install.packages("BiocManager")
BiocManager::install("mixOmics")
```

Below also works without any bugs - it skips mixOmics, but does not error out:
```
library(devtools)
devtools::install_github("rikenbit/iTensor") 
```

**Comment by kokitsuyuzaki** [comment]
As you said, I found that `mixOmics` was not automatically installed in some environment.
I'm not sure the reason but to explicitly install `mixOmics`, I changed the command as follows:

```
install.packages("BiocManager")
BiocManager::install(c("mixOmics", "iTensor"))
```

Please see the latest version of the manuscript.
https://github.com/openjournals/joss-reviews/issues/5496#issuecomment-1586735597
